### ISSUE TITLE
Sprint Day (2018 DKAN Open Data Summit)

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#151]
We will host a DKAN sprint during 2018 Drupal GovCon Sprint Day.

To-do:

- [ ] date/time/location ( @dafeder )
- [ ] short description (who should attend, what will happen) ( @dafeder )
- [ ] add to /summit
- [ ] ask @prynncamm questions (see below)
- [ ] add issues to GitHub
- [ ] promote to DKAN community

Questions for @prynncamm:

- [x] How do we get on promotions for that?
- [x] What are the logistics for this?
- [x] Anything else we should know?

**Comment by lukefretwell** [comment]
@kimwdavidson do you want to be POC on all things DKAN sprint?

**Comment by prynncamm** [comment]
I'm double-checking on Jess's schedule for promos and will follow-up here when I hear back!

**Comment by kimwdavidson** [comment]
@prynncamm Just checking in!

**Comment by lukefretwell** [comment]
@dafeder @kimwdavidson can we get the following info:

* Description of event
* Location/date

**Comment by kimwdavidson** [comment]
@lukefretwell This is the Saturday after GovCon, and it's in the sprint day room. We're just trying to join the existing sprint day

**Comment by lukefretwell** [comment]
@dafeder @kimwdavidson closing this since it's a non-issue now.

**Comment by kimwdavidson** [comment]
Sprint day was canceled, but we'd like to do all day sprint day + office hours on Friday. Dan is checking in with the organizers to see if that's okay

**Comment by dafeder** [comment]
Sprint day is not canceled! There has been some confusion and miscommunication with GovCon organizers but we are on for Friday instead of Saturday, which means missing some sessions but also a better possibility we'll get people stopping by. @lukefretwell last minute I know but here is some copy for the website.

DKAN D8 Open Sprint Day
Friday, Aug 24, 10am-4pm in the Coders Lounge

On the final day of Drupal GovCon, stop by the Coders Lounge to see what the DKAN team is working on for our next major version. While we're still an early prototyping phase of DKAN on Drupal 8, there's already a lot to work on and some exciting architectural changes to discuss! Drop by, grab an issue if you are a developer (front-end or back-end), or just sit down to chat about the future of Open Data on Drupal with CivicActions engineers and others.
