### ISSUE TITLE
DKAN 2 demo site

### ISSUE THREAD

**Issue by janette** [GetDKAN/ops#163]
## To do
- [x] Release Tag builds to a publicly available URL, no build numbers (e.g. https://demo.getdkan.com) and remains built until the next tag is released or a manual rebuild
- [ ] Rebuild nightly
- [ ] URL set up

**Comment by dharizza** [comment]
First item here is done.
We're creating demo sites per branch, so:
- builds triggered on master will be hosted in https://dkan2.ci.civicactions.net/
- any other branch will have a test site in an url similar to dkan-[BRANCH_NAME].ci.civicactions.net for example https://dkan-compose-project-name.ci.civicactions.net/

We still have to:
- Cleanup stale QA sites after some time has passed.
- Confirm if we want to run tests on branches, I'd say no because this is not the dkan2 repo, it is the dkan2 demo site.

The idea with this repo is to update the demo site every time a new dkan2 release is created, we can do it manually or automatically, if we want to do it automatically we can do so by adding a Jenkinsfile to dkan2 similar to https://github.com/GetDKAN/dkan/blob/7.x-1.x/Jenkinsfile but the stage should be something similar to:

```
stage('Rebuild demo site') {
  when { buildingTag() }
  steps {
    sh("git clone https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@git.civicactions.net/dkan/dkan-demo --tags")
    dir('dkan-demo') {
      # update Dockerfile
      sed -i -e "s/ENV TAG 3.0.0-rc17/ENV TAG ${TAG_NAME}/g" DOCKERFILE
      sh "git add . -A && git commit -m 'Update demo to dkan ${TAG_NAME} release'"
      sh "git push https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@git.civicactions.net/dkan/dkan-demo master"
    }
  }
}

**Comment by janette** [comment]
- [ ] Update the demo site every time a new dkan2 release is created

**Comment by janette** [comment]
@dasumner the repo for the demo site is https://git.civicactions.net/dkan/dkan-demo and currently it can be found at https://dkan2.ci.civicactions.net/

When the dkan 2.0 release is ready we would like the demo site to resolve at `demo.getdkan.com`

**Comment by dasumner** [comment]
Per Owen, DNS is managed by CloudFlare.
