### ISSUE TITLE
DKAN working group

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#34]
Create a DKAN working group with folks from public and private sector.

See what CKAN has done:

* https://ckan.org/about/association/
* https://ckan.org/about/government-working-group/
* https://ckan.org/about/steering-group/

**Comment by marctjones** [comment]
I think this means identifying project leaders. The CKAN association says it is a mechanism for supporting the development of CKAN. The purpose of membership being "By becoming a member you are helping to ensure the long-term sustainability of CKAN."

Since CivicActions is sponsoring the development of the product, I wonder if it is worth putting effort into recruiting members to an association to pay for a project. CKAN is sponsored by a nonprofit, so might be an easier sell for them to ask for essentially monetary donations to support the project.

On the other hand the association does also recognize a technical team who is compose of the official committers to the CKAN code base. If we want to grow the contributors to DKAN, we might want to consider what the standard would be for giving commit access to a non-civicactions employee to the official DKAN code base (as oppose to just letting people putting in pull requests to be reviewed by a CivicActioner.) 

Most company sponsored projects usually control commit access pretty closely, but that doesn't mean we have to. But we should think about the implications of doing so.

**Comment by lukefretwell** [comment]
@kimwdavidson I now think this is creating a level of bureaucracy we don't really need. Maybe at some point in the future, but seems like being more fluid and ad hoc right now is best approach.

If you 👍 can you close this issue?
