### ISSUE TITLE
Determine a process for a community helpdesk

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#52]
This may have been resolved and has yet to be documented, but would be great to communicate community support options and how/where to manage them. 

Example, there are questions in the general DKAN Slack channel, but perhaps there should be a specific #support channel with the indication that it's community and free and people should expect latency. Once someone submits a ticket, it might be best to document in GitHub (either in the /dkan repo or a /community-support repo). That way it can be acknowledged, reviewed and responded to in an efficient and collaborative way outside of just a Slack convo.

@dafeder @kimwdavidson

**Comment by kimwdavidson** [comment]
I love this idea, but I just don't think we have the capacity right now to make it happen. Everyone's hands are pretty full with just client support. I think ideally, we'd want people to use Slack to help each other, but we want those conversations to take place in the relevant channels vs. a support channel, I think.

**Comment by marctjones** [comment]
Even with commercial sponsored options it is not uncommon for the community to support itself. A lot of times a distinction is made between a public mailing list for users or something that anyone can join, and a official way to submit support requests for paying customers.

The expectation being if you send a message to a community forum, anyone or no one may respond to you. Often mailing lists are used, so that people can respond at a more leisurely pace then is often demanded by IRC/slack.

Similar with reporting bugs or asking for support issues. Anyone is usually able to open a ticket in github, but if it is an official support request then there is a procedure for paying customers to make an official request, so that the support providers can see who is submitting requests on behalf of paying customers.

**Comment by lukefretwell** [comment]
Per discussion, will direct folks to submit issues to /dkan repo and respond there. cc @kimwdavidson
